export const FETCH_LIENS = 'FETCH_LIENS';
export const FETCH_LIENS_START = 'FETCH_LIENS_START';
export const FETCH_LIENS_SUCCESS = 'FETCH_LIENS_SUCCESS';
export const FETCH_LIENS_FAIL = 'FETCH_LIENS_FAIL';
export const CLEAR_LIENS = 'CLEAR_LIENS';
export const CLEAR_LIENS_DATA = 'CLEAR_LIENS_DATA';

export const FETCH_LIEN = 'FETCH_LIEN';
export const FETCH_LIEN_SUCCESS = 'FETCH_LIEN_SUCCESS';
export const FETCH_LIEN_FAIL = 'FETCH_LIEN_FAIL';
export const CLEAR_LIEN = 'CLEAR_LIEN';

export const CLEAR_UPDATE_LIEN = 'CLEAR_UPDATE_LIEN';
export const UPDATE_LIEN = 'UPDATE_LIEN';
export const UPDATE_LIEN_SUCCESS = 'UPDATE_LIEN_SUCCESS';
export const UPDATE_LIEN_FAIL = 'UPDATE_LIEN_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const JUST_LOGGED_IN = 'JUST_LOGGED_IN';
export const TOKEN_MESSAGE = 'TOKEN_MESSAGE';
