export const FETCH_LIENS = 'FETCH_LIENS';
export const FETCH_LIENS_START = 'FETCH_LIENS_START';
export const FETCH_LIENS_SUCCESS = 'FETCH_LIENS_SUCCESS';
export const FETCH_LIENS_FAIL = 'FETCH_LIENS_FAIL';
export const CLEAR_LIENS = 'CLEAR_LIENS';

export const FETCH_LIEN = 'FETCH_LIEN';
export const FETCH_LIEN_SUCCESS = 'FETCH_LIEN_SUCCESS';
export const FETCH_LIEN_FAIL = 'FETCH_LIEN_FAIL';
export const CLEAR_LIEN = 'CLEAR_LIEN';

export const CLEAR_UPDATE_LIEN = 'CLEAR_UPDATE_LIEN';
export const UPDATE_LIEN = 'UPDATE_LIEN';
export const UPDATE_LIEN_SUCCESS = 'UPDATE_LIEN_SUCCESS';
export const UPDATE_LIEN_FAIL = 'UPDATE_LIEN_FAIL';
