export const FETCH_LIENS = 'FETCH_LIENS';
export const FETCH_LIENS_START = 'FETCH_LIENS_START';
export const FETCH_LIENS_SUCCESS = 'FETCH_LIENS_SUCCESS';
export const FETCH_LIENS_FAIL = 'FETCH_LIENS_FAIL';

export const FETCH_LIEN = 'FETCH_LIEN';
export const FETCH_LIEN_SUCCESS = 'FETCH_LIEN_SUCCESS';
export const FETCH_LIEN_FAIL = 'FETCH_LIEN_FAIL';
export const CLEAR_LIEN_ERROR = 'CLEAR_LIEN_ERROR';
